FROM frappe/bench:version-14

WORKDIR /home/frappe

COPY apps ./apps
COPY sites ./sites

ENV SITE_NAME=Newsite.localhost

ENV DB_HOST=mysql-1cd52d52-sriakila29125-4c07.e.aivencloud.com
ENV DB_PORT=17239
ENV DB_NAME=defaultdb
ENV DB_PASSWORD=CHANGE_ME_DB_PASSWORD

ENV REDIS_CACHE=CHANGE_ME_REDIS_URL
ENV REDIS_QUEUE=CHANGE_ME_REDIS_URL
ENV REDIS_SOCKETIO=CHANGE_ME_REDIS_URL

EXPOSE 8000

CMD ["bench", "start"]
